package dk.kea.sem2.exp;
// Generated Feb 11, 2015 8:14:29 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Runde2 generated by hbm2java
 */
@Entity
@Table(name="Runde2"
    ,schema="dbo"
    ,catalog="Electives"
)
public class Runde2  implements java.io.Serializable {


     private int valgfagId;
     private Valgfag valgfag;
     private Serializable pulje;

    public Runde2() {
    }

    public Runde2(int valgfagId, Valgfag valgfag, Serializable pulje) {
       this.valgfagId = valgfagId;
       this.valgfag = valgfag;
       this.pulje = pulje;
    }
   
     @Id 
    
    @Column(name="valgfag_id", unique=true, nullable=false)
    public int getValgfagId() {
        return this.valgfagId;
    }
    
    public void setValgfagId(int valgfagId) {
        this.valgfagId = valgfagId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="valgfag_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Valgfag getValgfag() {
        return this.valgfag;
    }
    
    public void setValgfag(Valgfag valgfag) {
        this.valgfag = valgfag;
    }
    
    @Column(name="pulje", nullable=false)
    public Serializable getPulje() {
        return this.pulje;
    }
    
    public void setPulje(Serializable pulje) {
        this.pulje = pulje;
    }




}


