package dk.kea.sem2.exp;
// Generated Feb 11, 2015 7:30:07 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * Runde2 generated by hbm2java
 */
public class Runde2  implements java.io.Serializable {


     private int valgfagId;
     private Valgfag valgfag;
     private Serializable pulje;

    public Runde2() {
    }

    public Runde2(int valgfagId, Valgfag valgfag, Serializable pulje) {
       this.valgfagId = valgfagId;
       this.valgfag = valgfag;
       this.pulje = pulje;
    }
   
    public int getValgfagId() {
        return this.valgfagId;
    }
    
    public void setValgfagId(int valgfagId) {
        this.valgfagId = valgfagId;
    }
    public Valgfag getValgfag() {
        return this.valgfag;
    }
    
    public void setValgfag(Valgfag valgfag) {
        this.valgfag = valgfag;
    }
    public Serializable getPulje() {
        return this.pulje;
    }
    
    public void setPulje(Serializable pulje) {
        this.pulje = pulje;
    }




}


