package dk.kea.sem2.exp;
// Generated Feb 11, 2015 8:14:29 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Runde1res generated by hbm2java
 */
@Entity
@Table(name="Runde1res"
    ,schema="dbo"
    ,catalog="Electives"
)
public class Runde1res  implements java.io.Serializable {


     private Serializable email;
     private Studerende studerende;
     private Valgfag valgfagByP1b;
     private Valgfag valgfagByP2a;
     private Valgfag valgfagByP1a;
     private Valgfag valgfagByP2b;

    public Runde1res() {
    }

    public Runde1res(Serializable email, Studerende studerende, Valgfag valgfagByP1b, Valgfag valgfagByP2a, Valgfag valgfagByP1a, Valgfag valgfagByP2b) {
       this.email = email;
       this.studerende = studerende;
       this.valgfagByP1b = valgfagByP1b;
       this.valgfagByP2a = valgfagByP2a;
       this.valgfagByP1a = valgfagByP1a;
       this.valgfagByP2b = valgfagByP2b;
    }
   
     @Id 
    
    @Column(name="Email", unique=true, nullable=false)
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Email", unique=true, nullable=false, insertable=false, updatable=false)
    public Studerende getStuderende() {
        return this.studerende;
    }
    
    public void setStuderende(Studerende studerende) {
        this.studerende = studerende;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="p1b", nullable=false)
    public Valgfag getValgfagByP1b() {
        return this.valgfagByP1b;
    }
    
    public void setValgfagByP1b(Valgfag valgfagByP1b) {
        this.valgfagByP1b = valgfagByP1b;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="p2a", nullable=false)
    public Valgfag getValgfagByP2a() {
        return this.valgfagByP2a;
    }
    
    public void setValgfagByP2a(Valgfag valgfagByP2a) {
        this.valgfagByP2a = valgfagByP2a;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="p1a", nullable=false)
    public Valgfag getValgfagByP1a() {
        return this.valgfagByP1a;
    }
    
    public void setValgfagByP1a(Valgfag valgfagByP1a) {
        this.valgfagByP1a = valgfagByP1a;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="p2b", nullable=false)
    public Valgfag getValgfagByP2b() {
        return this.valgfagByP2b;
    }
    
    public void setValgfagByP2b(Valgfag valgfagByP2b) {
        this.valgfagByP2b = valgfagByP2b;
    }




}


