package dk.kea.sem2.exp;
// Generated Feb 11, 2015 8:14:29 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Runde1 generated by hbm2java
 */
@Entity
@Table(name="Runde1"
    ,schema="dbo"
    ,catalog="Electives"
)
public class Runde1  implements java.io.Serializable {


     private int valgfagId;
     private Valgfag valgfag;

    public Runde1() {
    }

    public Runde1(int valgfagId, Valgfag valgfag) {
       this.valgfagId = valgfagId;
       this.valgfag = valgfag;
    }
   
     @Id 
    
    @Column(name="valgfag_id", unique=true, nullable=false)
    public int getValgfagId() {
        return this.valgfagId;
    }
    
    public void setValgfagId(int valgfagId) {
        this.valgfagId = valgfagId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="valgfag_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Valgfag getValgfag() {
        return this.valgfag;
    }
    
    public void setValgfag(Valgfag valgfag) {
        this.valgfag = valgfag;
    }




}


