package dk.kea.sem2.exp;
// Generated Feb 11, 2015 8:14:29 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Runde2res generated by hbm2java
 */
@Entity
@Table(name="Runde2res"
    ,schema="dbo"
    ,catalog="Electives"
)
public class Runde2res  implements java.io.Serializable {


     private Serializable email;
     private Studerende studerende;
     private Valgfag valgfagByBp1;
     private Valgfag valgfagByAp1;
     private Valgfag valgfagByBp2;
     private Valgfag valgfagByAp2;

    public Runde2res() {
    }

    public Runde2res(Serializable email, Studerende studerende, Valgfag valgfagByBp1, Valgfag valgfagByAp1, Valgfag valgfagByBp2, Valgfag valgfagByAp2) {
       this.email = email;
       this.studerende = studerende;
       this.valgfagByBp1 = valgfagByBp1;
       this.valgfagByAp1 = valgfagByAp1;
       this.valgfagByBp2 = valgfagByBp2;
       this.valgfagByAp2 = valgfagByAp2;
    }
   
     @Id 
    
    @Column(name="Email", unique=true, nullable=false)
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Email", unique=true, nullable=false, insertable=false, updatable=false)
    public Studerende getStuderende() {
        return this.studerende;
    }
    
    public void setStuderende(Studerende studerende) {
        this.studerende = studerende;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bp1", nullable=false)
    public Valgfag getValgfagByBp1() {
        return this.valgfagByBp1;
    }
    
    public void setValgfagByBp1(Valgfag valgfagByBp1) {
        this.valgfagByBp1 = valgfagByBp1;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ap1", nullable=false)
    public Valgfag getValgfagByAp1() {
        return this.valgfagByAp1;
    }
    
    public void setValgfagByAp1(Valgfag valgfagByAp1) {
        this.valgfagByAp1 = valgfagByAp1;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bp2", nullable=false)
    public Valgfag getValgfagByBp2() {
        return this.valgfagByBp2;
    }
    
    public void setValgfagByBp2(Valgfag valgfagByBp2) {
        this.valgfagByBp2 = valgfagByBp2;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ap2", nullable=false)
    public Valgfag getValgfagByAp2() {
        return this.valgfagByAp2;
    }
    
    public void setValgfagByAp2(Valgfag valgfagByAp2) {
        this.valgfagByAp2 = valgfagByAp2;
    }




}


