package dk.kea.sem2.exp;
// Generated Feb 11, 2015 7:30:07 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * Runde1res generated by hbm2java
 */
public class Runde1res  implements java.io.Serializable {


     private Serializable email;
     private Studerende studerende;
     private Valgfag valgfagByP1b;
     private Valgfag valgfagByP2a;
     private Valgfag valgfagByP1a;
     private Valgfag valgfagByP2b;

    public Runde1res() {
    }

    public Runde1res(Serializable email, Studerende studerende, Valgfag valgfagByP1b, Valgfag valgfagByP2a, Valgfag valgfagByP1a, Valgfag valgfagByP2b) {
       this.email = email;
       this.studerende = studerende;
       this.valgfagByP1b = valgfagByP1b;
       this.valgfagByP2a = valgfagByP2a;
       this.valgfagByP1a = valgfagByP1a;
       this.valgfagByP2b = valgfagByP2b;
    }
   
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Studerende getStuderende() {
        return this.studerende;
    }
    
    public void setStuderende(Studerende studerende) {
        this.studerende = studerende;
    }
    public Valgfag getValgfagByP1b() {
        return this.valgfagByP1b;
    }
    
    public void setValgfagByP1b(Valgfag valgfagByP1b) {
        this.valgfagByP1b = valgfagByP1b;
    }
    public Valgfag getValgfagByP2a() {
        return this.valgfagByP2a;
    }
    
    public void setValgfagByP2a(Valgfag valgfagByP2a) {
        this.valgfagByP2a = valgfagByP2a;
    }
    public Valgfag getValgfagByP1a() {
        return this.valgfagByP1a;
    }
    
    public void setValgfagByP1a(Valgfag valgfagByP1a) {
        this.valgfagByP1a = valgfagByP1a;
    }
    public Valgfag getValgfagByP2b() {
        return this.valgfagByP2b;
    }
    
    public void setValgfagByP2b(Valgfag valgfagByP2b) {
        this.valgfagByP2b = valgfagByP2b;
    }




}


