package dk.kea.sem2.exp;
// Generated Feb 11, 2015 8:14:29 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Studerende generated by hbm2java
 */
@Entity
@Table(name="Studerende"
    ,schema="dbo"
    ,catalog="Electives"
)
public class Studerende  implements java.io.Serializable {


     private Serializable email;
     private Serializable navn;
     private Integer harstemt1;
     private Integer harstem2;
     private Set<Runde2res> runde2reses = new HashSet<Runde2res>(0);
     private Set<Valgfag> valgfags = new HashSet<Valgfag>(0);
     private Set<Runde1res> runde1reses = new HashSet<Runde1res>(0);

    public Studerende() {
    }

	
    public Studerende(Serializable email, Serializable navn) {
        this.email = email;
        this.navn = navn;
    }
    public Studerende(Serializable email, Serializable navn, Integer harstemt1, Integer harstem2, Set<Runde2res> runde2reses, Set<Valgfag> valgfags, Set<Runde1res> runde1reses) {
       this.email = email;
       this.navn = navn;
       this.harstemt1 = harstemt1;
       this.harstem2 = harstem2;
       this.runde2reses = runde2reses;
       this.valgfags = valgfags;
       this.runde1reses = runde1reses;
    }
   
     @Id 
    
    @Column(name="Email", unique=true, nullable=false)
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    
    @Column(name="Navn", nullable=false)
    public Serializable getNavn() {
        return this.navn;
    }
    
    public void setNavn(Serializable navn) {
        this.navn = navn;
    }
    
    @Column(name="Harstemt1")
    public Integer getHarstemt1() {
        return this.harstemt1;
    }
    
    public void setHarstemt1(Integer harstemt1) {
        this.harstemt1 = harstemt1;
    }
    
    @Column(name="Harstem2")
    public Integer getHarstem2() {
        return this.harstem2;
    }
    
    public void setHarstem2(Integer harstem2) {
        this.harstem2 = harstem2;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studerende")
    public Set<Runde2res> getRunde2reses() {
        return this.runde2reses;
    }
    
    public void setRunde2reses(Set<Runde2res> runde2reses) {
        this.runde2reses = runde2reses;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="Finalvalgfag", schema="dbo", catalog="Electives", joinColumns = { 
        @JoinColumn(name="email", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="valgfag_id", nullable=false, updatable=false) })
    public Set<Valgfag> getValgfags() {
        return this.valgfags;
    }
    
    public void setValgfags(Set<Valgfag> valgfags) {
        this.valgfags = valgfags;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studerende")
    public Set<Runde1res> getRunde1reses() {
        return this.runde1reses;
    }
    
    public void setRunde1reses(Set<Runde1res> runde1reses) {
        this.runde1reses = runde1reses;
    }




}


