package dk.kea.sem2.exp;
// Generated Feb 11, 2015 7:30:07 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Studerende generated by hbm2java
 */
public class Studerende  implements java.io.Serializable {


     private Serializable email;
     private Serializable navn;
     private Integer harstemt1;
     private Integer harstem2;
     private Set runde2reses = new HashSet(0);
     private Set valgfags = new HashSet(0);
     private Set runde1reses = new HashSet(0);

    public Studerende() {
    }

	
    public Studerende(Serializable email, Serializable navn) {
        this.email = email;
        this.navn = navn;
    }
    public Studerende(Serializable email, Serializable navn, Integer harstemt1, Integer harstem2, Set runde2reses, Set valgfags, Set runde1reses) {
       this.email = email;
       this.navn = navn;
       this.harstemt1 = harstemt1;
       this.harstem2 = harstem2;
       this.runde2reses = runde2reses;
       this.valgfags = valgfags;
       this.runde1reses = runde1reses;
    }
   
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getNavn() {
        return this.navn;
    }
    
    public void setNavn(Serializable navn) {
        this.navn = navn;
    }
    public Integer getHarstemt1() {
        return this.harstemt1;
    }
    
    public void setHarstemt1(Integer harstemt1) {
        this.harstemt1 = harstemt1;
    }
    public Integer getHarstem2() {
        return this.harstem2;
    }
    
    public void setHarstem2(Integer harstem2) {
        this.harstem2 = harstem2;
    }
    public Set getRunde2reses() {
        return this.runde2reses;
    }
    
    public void setRunde2reses(Set runde2reses) {
        this.runde2reses = runde2reses;
    }
    public Set getValgfags() {
        return this.valgfags;
    }
    
    public void setValgfags(Set valgfags) {
        this.valgfags = valgfags;
    }
    public Set getRunde1reses() {
        return this.runde1reses;
    }
    
    public void setRunde1reses(Set runde1reses) {
        this.runde1reses = runde1reses;
    }




}


