package dk.kea.sem2.exp;
// Generated Feb 11, 2015 7:30:07 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Valgfag generated by hbm2java
 */
public class Valgfag  implements java.io.Serializable {


     private int valgfagId;
     private Serializable navn;
     private Serializable beskrivelse;
     private Serializable bpu;
     private Set runde1resesForP1a = new HashSet(0);
     private Set runde2resesForAp2 = new HashSet(0);
     private Set runde2s = new HashSet(0);
     private Set runde2resesForBp1 = new HashSet(0);
     private Set runde2resesForBp2 = new HashSet(0);
     private Set runde2resesForAp1 = new HashSet(0);
     private Set runde1s = new HashSet(0);
     private Set studerendes = new HashSet(0);
     private Set runde1resesForP2a = new HashSet(0);
     private Set runde1resesForP1b = new HashSet(0);
     private Set runde1resesForP2b = new HashSet(0);

    public Valgfag() {
    }

	
    public Valgfag(int valgfagId, Serializable navn, Serializable bpu) {
        this.valgfagId = valgfagId;
        this.navn = navn;
        this.bpu = bpu;
    }
    public Valgfag(int valgfagId, Serializable navn, Serializable beskrivelse, Serializable bpu, Set runde1resesForP1a, Set runde2resesForAp2, Set runde2s, Set runde2resesForBp1, Set runde2resesForBp2, Set runde2resesForAp1, Set runde1s, Set studerendes, Set runde1resesForP2a, Set runde1resesForP1b, Set runde1resesForP2b) {
       this.valgfagId = valgfagId;
       this.navn = navn;
       this.beskrivelse = beskrivelse;
       this.bpu = bpu;
       this.runde1resesForP1a = runde1resesForP1a;
       this.runde2resesForAp2 = runde2resesForAp2;
       this.runde2s = runde2s;
       this.runde2resesForBp1 = runde2resesForBp1;
       this.runde2resesForBp2 = runde2resesForBp2;
       this.runde2resesForAp1 = runde2resesForAp1;
       this.runde1s = runde1s;
       this.studerendes = studerendes;
       this.runde1resesForP2a = runde1resesForP2a;
       this.runde1resesForP1b = runde1resesForP1b;
       this.runde1resesForP2b = runde1resesForP2b;
    }
   
    public int getValgfagId() {
        return this.valgfagId;
    }
    
    public void setValgfagId(int valgfagId) {
        this.valgfagId = valgfagId;
    }
    public Serializable getNavn() {
        return this.navn;
    }
    
    public void setNavn(Serializable navn) {
        this.navn = navn;
    }
    public Serializable getBeskrivelse() {
        return this.beskrivelse;
    }
    
    public void setBeskrivelse(Serializable beskrivelse) {
        this.beskrivelse = beskrivelse;
    }
    public Serializable getBpu() {
        return this.bpu;
    }
    
    public void setBpu(Serializable bpu) {
        this.bpu = bpu;
    }
    public Set getRunde1resesForP1a() {
        return this.runde1resesForP1a;
    }
    
    public void setRunde1resesForP1a(Set runde1resesForP1a) {
        this.runde1resesForP1a = runde1resesForP1a;
    }
    public Set getRunde2resesForAp2() {
        return this.runde2resesForAp2;
    }
    
    public void setRunde2resesForAp2(Set runde2resesForAp2) {
        this.runde2resesForAp2 = runde2resesForAp2;
    }
    public Set getRunde2s() {
        return this.runde2s;
    }
    
    public void setRunde2s(Set runde2s) {
        this.runde2s = runde2s;
    }
    public Set getRunde2resesForBp1() {
        return this.runde2resesForBp1;
    }
    
    public void setRunde2resesForBp1(Set runde2resesForBp1) {
        this.runde2resesForBp1 = runde2resesForBp1;
    }
    public Set getRunde2resesForBp2() {
        return this.runde2resesForBp2;
    }
    
    public void setRunde2resesForBp2(Set runde2resesForBp2) {
        this.runde2resesForBp2 = runde2resesForBp2;
    }
    public Set getRunde2resesForAp1() {
        return this.runde2resesForAp1;
    }
    
    public void setRunde2resesForAp1(Set runde2resesForAp1) {
        this.runde2resesForAp1 = runde2resesForAp1;
    }
    public Set getRunde1s() {
        return this.runde1s;
    }
    
    public void setRunde1s(Set runde1s) {
        this.runde1s = runde1s;
    }
    public Set getStuderendes() {
        return this.studerendes;
    }
    
    public void setStuderendes(Set studerendes) {
        this.studerendes = studerendes;
    }
    public Set getRunde1resesForP2a() {
        return this.runde1resesForP2a;
    }
    
    public void setRunde1resesForP2a(Set runde1resesForP2a) {
        this.runde1resesForP2a = runde1resesForP2a;
    }
    public Set getRunde1resesForP1b() {
        return this.runde1resesForP1b;
    }
    
    public void setRunde1resesForP1b(Set runde1resesForP1b) {
        this.runde1resesForP1b = runde1resesForP1b;
    }
    public Set getRunde1resesForP2b() {
        return this.runde1resesForP2b;
    }
    
    public void setRunde1resesForP2b(Set runde1resesForP2b) {
        this.runde1resesForP2b = runde1resesForP2b;
    }




}


